servers:
  ovh-host-01: {hostname: "ovh-host-01.qf3l3k.cloud", processing: "local", rule_path: "G:/Temp/Sync/20240906/ovh-host-01.qf3l3k.cloud/etc/ufw"}
  ovh-host-02: {hostname: "ovh-host-02.qf3l3k.cloud", processing: "local", rule_path: "G:/Temp/Sync/20240906/ovh-host-02.qf3l3k.cloud/etc/ufw"}
  ovh-host-03: {hostname: "ovh-host-03.qf3l3k.cloud", processing: "local", rule_path: "G:/Temp/Sync/20240906/ovh-host-03.qf3l3k.cloud/etc/ufw"}
  ovh-host-04: {hostname: "ovh-host-04.qf3l3k.cloud", processing: "local", rule_path: "G:/Temp/Sync/20240906/ovh-host-04.qf3l3k.cloud/etc/ufw"}
  server2: {hostname: "server2.example.com", processing: "remote", use_ssh_agent: false, ssh_user: "user", ssh_key: "/path/to/private/key"}
  server3: {hostname: "server3.example.com", processing: "remote", use_ssh_agent: true}
